/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HabitacionesRouteImport } from './routes/habitaciones'
import { Route as ReservasRouteImport } from './routes/reservas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitacionesRoute = HabitacionesRouteImport.update({
  id: '/habitaciones',
  path: '/habitaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasRoute = ReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/habitaciones': typeof HabitacionesRoute
  '/reservas': typeof ReservasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/habitaciones': typeof HabitacionesRoute
  '/reservas': typeof ReservasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/habitaciones': typeof HabitacionesRoute
  '/reservas': typeof ReservasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/habitaciones' | '/reservas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/habitaciones' | '/reservas'
  id: '__root__' | '/' | '/habitaciones' | '/reservas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HabitacionesRoute: typeof HabitacionesRoute
  ReservasRoute: typeof ReservasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habitaciones': {
      id: '/habitaciones'
      path: '/habitaciones'
      fullPath: '/habitaciones'
      preLoaderRoute: typeof HabitacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas': {
      id: '/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HabitacionesRoute: HabitacionesRoute,
  ReservasRoute: ReservasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
